Feature/testing
ecmwf/conflator pull request #6
Opened 2024-02-27 12:45 UTC by mathleur

Add some tests

2024-03-01 15:15 UTC, jameshawkes requested changes

2024-03-01 15:15 UTC, jameshawkes commented on tests/test_load_conflator.py
Remove the polytope-like examples. If they test something useful, just rewrite it without the domain-specific terminology :)

2024-03-01 15:15 UTC, jameshawkes commented on tests/test_nested_subclasses.py
Same here

2024-03-05 15:26 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/conflator?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/conflator?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/conflator?pullRequest=6) it.</sub>

2024-03-05 15:27 UTC, merged